### ISSUE TITLE
Logging of un-handled exceptions

### ISSUE THREAD

**Issue by Twinsen-** [margatampu/laravel-teams-logging#1]
I have a problem configuring teams-logging !

It works perfectly when the exception is catched and my code do the \Log::xxxx().

But on unhandled exceptions, I have the log and stacktrace into my "single" channel, but nothing in "teams" channel.

Might be a configuration problem or an issue ??

Thanks.
NC.

**Comment by margatampu** [comment]
Hello @Twinsen- 

Is it working when you logging message using simple code like this in your route file?
`
Route::get('/example', function(){
    Log::channel('teams')->error('Error message');
});
`

If it is, let me know so I can tracking this issue. But if isn't, maybe you have some misconfiguration.

Just let me know whatever it is?

**Comment by margatampu** [comment]
Hi @Twinsen- 

Can you give me your code snippet when do the exceptions?

**Comment by Twinsen-** [comment]
Hi ! 
My code is fine when I log events :
`\Log::error("error message");`
`\Log::channel('teams')->error('error message');`

These are well logged to teams.

My problem is when an exception is not catched. when laravel catch it, it is logged in the log file but not send to 'teams' channel.

in my logging.php file, default is stack, and stack is single + teams

logging.php

_<?php
use Monolog\Handler\StreamHandler;
use Monolog\Handler\SyslogUdpHandler;
return [
    'default' => env('LOG_CHANNEL', 'stack'),

    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['single', 'teams'],
            'ignore_exceptions' => false,
        ],
        'single' => [
            'driver' => 'single',
            'path' => storage_path('logs/laravel.log'),
            'level' => env('APP_LOG_LEVEL', 'debug'),
        ],
     .....
        'teams' => [
            'driver'    => 'custom',
            'via'       => \MargaTampu\LaravelTeamsLogging\LoggerChannel::class,
            'level'     => 'error',
            'url'       => env('INCOMING_WEBHOOK_URL'),
            'style'     => 'card',    // Available style is 'simple' and 'card', default is 'simple'
            'name'      => 'MonDiagamter'
        ],
    ],
];_

**Comment by margatampu** [comment]
Hi @Twinsen-,

In your configurable file, your single array, level use value from **APP_LOG_LEVEL** or **debug** as default, and in team array, level use **error**. 

Since the log using priority from debug as the lowest to emergency as the highest ('emergency', 'alert', 'critical', 'error', 'warning', 'notice', 'info', 'debug').

Maybe in some point, your log process has level lower than error and teams doesn't send the message but log still process it.

To make sure that single and teams has the same level value, you can use this configurable for teams.

`'teams' => [
        'driver'    => 'custom',
        'via'       => \MargaTampu\LaravelTeamsLogging\LoggerChannel::class,
        **'level' => env('APP_LOG_LEVEL', 'debug'),**
        'url'       => env('INCOMING_WEBHOOK_URL'),
        'style'     => 'card',    // Available style is 'simple' and 'card', default is 'simple'
        'name'      => 'MonDiagamter'
    ],`

Please let me know if it works.

**Comment by Twinsen-** [comment]
Hello,
I just tested with the same 'level' and the problem is still present.
But I will stop bothering you and look for Monolog or Handlers in my laravel instance because the problem may come from there...
Since my laravel instance is an update from version 4, some configurations must be bad ...
I keep you informed of my research, thank you again for your time!

Regards,
Nicolas.

**Comment by margatampu** [comment]
Ok @Twinsen-,

Let me know your research results.

Thanks

**Comment by jamespavett** [comment]
@margatampu I am having the same issue.

Un-handled exceptions will log via stack to other channels like single, however no response is generated within teams for the errors.
