### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by guastallaigor** [margatampu/laravel-teams-logging#5]
Hello, I would like to try to use this dependency in some of my projects. But I've already upgraded all of them to Laravel 6 and there's a problem with monolog when I'm trying to install this dependency:

![image](https://user-images.githubusercontent.com/22016005/64859076-a39f1780-d5ff-11e9-9812-19199f5ec540.png)

If you can, please update monolog to 2.0.0, I think this should work.

**Comment by margatampu** [comment]
Hi @guastallaigor, since Laravel 6 not release officially, I can update it. I will wait until Laravel 6 release and update it to prevent another errors appear.

**Comment by margatampu** [comment]
Until then, I will let this issue open and back again in the future.

**Comment by guastallaigor** [comment]
Thank you for your reply.
According to Laravel News, Laravel 6 was released officially on September 03, check out this [link](https://laravel-news.com/laravel-6).
Right now Laravel is on version 6.4, according to [this](https://laravel-news.com/laravel-6-4) and [this](https://github.com/laravel/framework/releases/tag/v6.4.0).
But it's fine, tbh I was already looking into another alternatives to this.

**Comment by margatampu** [comment]
Hi @guastallaigor,

I am so sorry. There is some minor error on laravel documentation I think. It will install laravel 5.8 using composer, but install laravel 6.4 using laravel installer. 

I will look to this issue. Even you found another package like this, I will say thank you for stopping by.

best regards,

**Comment by margatampu** [comment]
monolog updated
