### ISSUE TITLE
Card style not being sent

### ISSUE THREAD

**Issue by felipeneuhauss** [margatampu/laravel-teams-logging#7]
Hi! Thanks for your contribution.

I have being using your component and it worked properly to simple message style.

But when I try to receive a card style, it doesn't work.

Are there different configurations to a card style?

Thank you so much.

**Comment by margatampu** [comment]
Hi @felipeneuhauss, thank you for open issue.

I found it quite good and there is no issue when switching between 'card' or 'simple'.

Can you inform me more about your laravel and laravel-teams-logging versions you currently ran/installed.

Thank you,

**Comment by felipeneuhauss** [comment]
Hi @margatampu, sure. Here some details:

**package.json**

`"laravel/lumen-framework": "5.8.*",`
`"margatampu/laravel-teams-logging": "^1.2",`

**Some place into a Validation custom class:**

`\Illuminate\Support\Facades\Log::error( env('APP_ENV') . ' - ' . $messa, $this->value);`

**logging.php**
```
'teams' => [
            'driver' => 'custom',
            'via' => MargaTampu\LaravelTeamsLogging\LoggerChannel::class,
            'level' => 'warning',
            'url' => env('INCOMING_WEBHOOK_URL'),
            'style' => 'card',    // Available style is 'simple' and 'card', default is 'simple'
            'name' => 'pt.edd.webservices.messaging'
        ],
```

**app/bootstrap.php**

/*
 * Teams log integration
 */
```
$app->register(\MargaTampu\LaravelTeamsLogging\LoggerServiceProvider::class);
$app->configure('teams');
```

Well, that's all. I'm using lumen. 

Am I doing some thing wrong?

Thanks!

**Comment by matalina** [comment]
I realize this is an old issue, but I am unable to change the style from simple to card.  Simple works fine.  But when I send it as a Card Style it does not go through.  
logging.php
```
teams' => [
            'driver' => 'custom',
            'via'       => \MargaTampu\LaravelTeamsLogging\LoggerChannel::class,
            'level' => 'debug',
            'url' => env('TEAMS_WEBHOOK_URL'),
            'name' => env('APP_NAME')
        ],
```
I can add ``'style' => 'simple'`` and it works but adding ``'style' => 'card'`` sends nothing.

composer.json
```
"margatampu/laravel-teams-logging": "^1.2",
"laravel/framework": "^7.13",
...
```

**Comment by matalina** [comment]
I have used taken the package and placed it in my app so that I can modify the card style to display as I needed it to, and found that it's the fact section that is preventing the message from going through. I don't know if this is a change in API or what but remove it and the cards work fine.  But I'll be using my version  your Liscense is still being displayed as I didn't write it just modified the code.
